const b64 = "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABmJLR0QA/wD/AP+gvaeTAAAACXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH6AIBDBcWpS8zHwAAAD1JREFUeN7t0EERAAAIA6HZvzQsYAcX9EkDDAAAAAAAAAAAAADA3oB7AwAAAAAAAAAAAADA3oB7AwAAAAAAAAAAsFsP5uUAt6JpXwAAAABJRU5ErkJggg==";
const buf = Buffer.from(b64, 'base64');
require('fs').writeFileSync('test.png', buf);
